version: '3'

services:
  app:
    build:
      context: ../.
      dockerfile: ./build/app/Dockerfile
    container_name: app
    restart: on-failure
    environment:
      WAIT_HOSTS: db:5432
    ports: 
      - ${APP_HTTP_PORT}:8123
      - ${APP_GRPC_PORT}:8765
    depends_on: 
      - db 
  db:
    image: postgres
    container_name: ab-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
  migrate:
    build:
      context: ../.
      dockerfile: ./build/migrate/Dockerfile
    container_name: app_migrate
    restart: on-failure
    environment:
      WAIT_HOSTS: db:5432
      DSN: "host=db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
    volumes:
      - ../migrations:/migrations
    depends_on: 
      - db 
