version: '3'

networks:
  integration:
    driver: bridge

services:
  integration:
    build:
      context: ../.
      dockerfile: ./build/tests/Dockerfile
    environment:
      WAIT_HOSTS: db:5432
      WAIT_AFTER: 3
      DSN: host=db user=homestead password=secret dbname=homestead sslmode=disable
    depends_on: 
      - db
    networks:
      - integration
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    networks:
      - integration
