AppConfig:
  NumberOfAttemptsForLogin: 10
  NumberOfAttemptsForPassword: 100
  NumberOfAttemptsForIP: 1000
LoggerConfig:
  Level: "DEBUG"
ServerConfig:
  Address: ":8123"
GrpcServerConfig:
  Address: ":8765"
DatabaseConfig:
  DSN: "host=localhost user=homestead password=secret dbname=homestead sslmode=disable"
